name: 'anchore-scan'
description: 'Docker image scan with anchore and produce output for downstream'
inputs:
  image_reference:  # id of input
    description: 'The image to scan'
    required: true
  dockerfile_path:
    description: 'Path to the dockerfile'
    required: false
  scan_scriptname:
    description: 'Scriptname for the action to use as override - for testing only'
    required: false    
  inline_scan_image:
    description: 'Full tag reference of anchore inline scan image to use as override'
    required: false
  debug:
    description: 'Set this to any value to enable verbose debug output'
    required: false
  fail_build:
    description: 'Set to any value to cause build to fail upon failed anchore policy evaluation'
    required: false
outputs:
  billofmaterials:
    description: 'The json output report specifying the content of the image'
  vulnerabilities:
    description: 'The found vulnerabilities for the image'
  policycheck:
    descrption: 'The json report for evaluating the image against the given policy, if present'
runs:
  using: 'node12'
  main: 'index.js'
