name: "[Demo] Run Scan Action"

on: [push, pull_request]

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./
        with:
          image: "alpine:latest"
          debug: true
          fail-build: false

  test-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./
        with:
          path: "tests/fixtures/npm-project"
          debug: true
          severity-cutoff: "negligible"
          fail-build: false

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./
        with:
          sbom: tests/fixtures/test_sbom.spdx.json
          debug: true
          fail-build: false
