name: "[SARIF] Run Scan Action"

on: [push, pull_request]

jobs:
  sarif-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run the local Scan Action with SARIF generation enabled
        id: scan
        uses: ./
        with:
          image: "debian:8"
          debug: true
          fail-build: false
          #severity-cutoff: "Medium"

      - name: Inspect Generated SARIF
        run: cat ${{ steps.scan.outputs.sarif }}

    # Commented out to prevent incorrect SARIF uploads for this action
    # TODO: add functional tests that validate this
    # - name: Upload SARIF
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarif }}

  sarif-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run the local Scan Action with SARIF generation enabled
        id: scan
        uses: ./
        with:
          path: "tests/fixtures/npm-project"
          debug: true
          fail-build: false
          #severity-cutoff: "Medium"

      - name: Inspect Generated SARIF
        run: cat ${{ steps.scan.outputs.sarif }}
    # Commented out to prevent incorrect SARIF uploads for this action
    # TODO: add functional tests that validate this
    # - name: Upload SARIF
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarif }}
