name: "Run Anchore Action"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - name: Run anchore action
      uses: ./
      with:
        image-reference: "alpine:latest"
