name: "Run JavaScript Action"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - name: Run anchore action
      uses: ./
      with:
        image_reference: "alpine:latest"
    - name: View anchore reports
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: Upload anchore scan reports
      uses: actions/upload-artifact@v1
      with:
        name: anchore-reports
        path: ./anchore-reports