name: "Tests"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly and there is no faked build ncc built scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: npm ci
      - run: npm run audit
      - run: npm run build
      - run: git status --porcelain
      - run: git diff
      - run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build images
        run: |
          for distro in alpine centos debian; do
            docker build -t localhost:5000/match-coverage/$distro ./tests/fixtures/image-$distro-match-coverage
            docker push localhost:5000/match-coverage/$distro:latest
          done
      - name: Inspect
        run: |
          docker images -a
          for distro in alpine centos debian; do
            docker buildx imagetools inspect localhost:5000/match-coverage/$distro:latest
          done
      - run: npm ci
      - run: npm run audit
      - run: npm test
