name: PR for latest Grype release
on:
  schedule:
    # 7:04 UTC (2:04 am EST)
    - cron: "4 7 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upgrade-grype:
    runs-on: ubuntu-latest
    if: github.repository == 'anchore/scan-action'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Get latest Grype version
        id: latest-version
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          LATEST_VERSION=$(gh release view --json name -q '.name' -R anchore/grype)
          echo "exports.GRYPE_VERSION = \"$LATEST_VERSION\";" > GrypeVersion.js
          # install husky hooks and dependencies:
          npm install
          npm run build
          # export the version for use with create-pull-request:
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@c55203cfde3e5c11a452d352b4393e68b85b4533 # v6.0.3
        with:
          signoff: true
          delete-branch: true
          branch: auto/latest-grype
          labels: dependencies
          commit-message: "chore(deps): update Grype to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          title: "chore(deps): update Grype to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          body: "Update Grype to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          token: ${{ steps.generate-token.outputs.token }}
